In [1]:
import numpy as np



In [8]:
# Crear un tensor de 5 dimensiones con forma (2, 3, 4, 5, 6)
tensor_5d = np.random.rand(1, 2, 3, 4, 5)

print(tensor_5d)
print("Forma del tensor:", tensor_5d.shape)

[[[[[0.02172165 0.88678345 0.22896336 0.90752305 0.77020304]
    [0.5679866  0.21770757 0.60840885 0.16498103 0.88907712]
    [0.13748731 0.66933294 0.20631269 0.30378847 0.62364758]
    [0.45163841 0.18634907 0.49311304 0.47318242 0.94324213]]

   [[0.50974152 0.43486548 0.73984795 0.25510993 0.01795929]
    [0.52783133 0.55827404 0.70326955 0.31409689 0.88987546]
    [0.69218219 0.5434169  0.29866103 0.09152263 0.03678332]
    [0.97631011 0.58424848 0.52865981 0.28843155 0.58392479]]

   [[0.8022345  0.77965158 0.69022171 0.30707999 0.12419391]
    [0.60324734 0.79969187 0.04797416 0.81528806 0.71689403]
    [0.85527439 0.43593392 0.93956182 0.30113258 0.08369691]
    [0.71349169 0.9037452  0.19849071 0.40827365 0.18268117]]]


  [[[0.3713191  0.04723028 0.69171552 0.5444821  0.38945363]
    [0.99950896 0.26531271 0.70877788 0.2091001  0.68783567]
    [0.89552337 0.89530854 0.57194572 0.09118277 0.46904712]
    [0.48570359 0.70298133 0.36934431 0.73013902 0.51898409]]

   [[0.1638910

In [9]:
# Añadir una nueva dimensión (de tamaño 1) al tensor
tensor_6d = np.expand_dims(tensor_5d, axis=0)

print("Forma del tensor original:", tensor_5d.shape)
print("Forma del tensor después de añadir una dimensión:", tensor_6d.shape)


Forma del tensor original: (1, 2, 3, 4, 5)
Forma del tensor después de añadir una dimensión: (1, 1, 2, 3, 4, 5)


In [13]:
print(tensor_6d.shape) #imprime la forma del nuevo tensor
print(tensor_6d) #muestra el contenido del tensor

(1, 1, 2, 3, 4, 5)
[[[[[[0.02172165 0.88678345 0.22896336 0.90752305 0.77020304]
     [0.5679866  0.21770757 0.60840885 0.16498103 0.88907712]
     [0.13748731 0.66933294 0.20631269 0.30378847 0.62364758]
     [0.45163841 0.18634907 0.49311304 0.47318242 0.94324213]]

    [[0.50974152 0.43486548 0.73984795 0.25510993 0.01795929]
     [0.52783133 0.55827404 0.70326955 0.31409689 0.88987546]
     [0.69218219 0.5434169  0.29866103 0.09152263 0.03678332]
     [0.97631011 0.58424848 0.52865981 0.28843155 0.58392479]]

    [[0.8022345  0.77965158 0.69022171 0.30707999 0.12419391]
     [0.60324734 0.79969187 0.04797416 0.81528806 0.71689403]
     [0.85527439 0.43593392 0.93956182 0.30113258 0.08369691]
     [0.71349169 0.9037452  0.19849071 0.40827365 0.18268117]]]


   [[[0.3713191  0.04723028 0.69171552 0.5444821  0.38945363]
     [0.99950896 0.26531271 0.70877788 0.2091001  0.68783567]
     [0.89552337 0.89530854 0.57194572 0.09118277 0.46904712]
     [0.48570359 0.70298133 0.36934431 0.73

In [20]:
# Eliminar las dimensiones de tamaño 1 (en este tensor hay dos "1")
tensor_4d = np.squeeze(tensor_6d)

# Verificar la forma del tensor después de eliminar la dimensión
print("Forma del tensor después de eliminar la dimensión:", tensor_4d.shape)

Forma del tensor después de eliminar la dimensión: (2, 3, 4, 5)
